### ISSUE TITLE
Twitter ignores second slash

### ISSUE THREAD

**Issue by kosvrouvas** [zws-im/zws#14] opened 2019-07-23 10:56 UTC
Twitter ignores second slash so when posted the shortlink doesn't work. This is probably a Twitter issue but just wanted to let you know.

Example:
![image](https://user-images.githubusercontent.com/3307723/61706739-8497ae00-ad51-11e9-8df3-cbee4cfd13b8.png)

**Comment by pizzafox** [comment] 2019-07-23 16:50
We're aware of the Twitter bug. Most likely it's Twitter filtering which characters are allowed to be in a URL.

**Comment by gabrodbr** [comment] 2019-07-23 16:50
try add # after the second slash (I don't have Twitter)

**Comment by pizzafox** [comment] 2019-07-23 16:55
That doesn't work either. Looking at the compose new tweet menu shows that both zero-width characters are being separated from the URL (`U200B` and `U200B` as of writing)

**Comment by pizzafox** [comment] 2019-08-08 23:46
I found the RegEx that Twitter uses to check for space characters:
```javascript
/\x09-\x0D\x20\x85\xA0\u1680\u180E\u2000-\u200A\u2028\u2029\u202F\u205F\u3000/
```

**Comment by MicroDroid** [comment] 2020-05-21 21:18
L

**Comment by MicroDroid** [comment] 2020-05-21 21:20
The problem is that Twitter sweeps too many characters, not sure if we can have like anything that works with Twitter at all? Even if we could it'd be very tricky. Also Twitter re-shortens URLs to use their own URL shortener anyways, so it doesn't give a lot of benefits.

@pizzafox what do you think?

**Comment by pizzafox** [comment] 2020-05-21 21:41
That RegExp for filtering what strings are marked as a URL is probably still pretty accurate. ZWS 2 is going to use a much larger set of characters, most of which from the [tags](https://en.wikipedia.org/wiki/Tags_(Unicode_block)) block. I just did a brief test now, and those aren't working either. It's unlikely we'll ever be able to get the characters to work on Twitter because of how strict they are with filtering URLs.

**Comment by MicroDroid** [comment] 2020-05-22 07:31
@pizzafox How does the ZWS list compare to that regex? Is it really that *all* is matched through the regex? I remember it was gigantic and infinitely long list

**Comment by pizzafox** [comment] 2020-05-22 07:35
> @pizzafox How does the ZWS list compare to that regex? Is it really that _all_ is matched through the regex? I remember it was gigantic and infinitely long list

Twitter is whitelisting characters that can be included in a URL, so anything not in a common range of characters will break the URL matching.

**Comment by MicroDroid** [comment] 2020-05-22 09:02
Ah, I didn't notice it is a whitelist thing. In that case I guess there's not much that can be done. I'll close this issue.

**Closed by MicroDroid** 2020-05-22 09:02 UTC
Labels: broken url, bug, twitter
